import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const [appSource, appStyles] = await Promise.all([
  readFile(new URL('../src/App.jsx', import.meta.url), 'utf8'),
  readFile(new URL('../src/styles.css', import.meta.url), 'utf8'),
])

assert.doesNotMatch(appSource, /FilmChallengeStatus|film-challenge-summary|toolbar-challenge-check|challengeResults|challengeFilms|activeChallengeFilm|captionChallengeFilm/, 'challenge feedback must not render inside Rainbow Studio')
assert.match(appSource, /function FilmProgressBookmark\(/, 'challenge feedback should use the bookmark notification')
assert.match(appSource, /const nextFilmNotifications = getFilmProgressChanges\(history, nextHistory\)/)
assert.match(appSource, /filmChallenges: createFilmChallenges\(completionSource, t\.defaultCaption\)/)
assert.match(appSource, /function backfillCaptionChallenges\(/)
assert.match(appSource, /ensureCustomCaptionChallenge\(day, defaultCaption\)/)
assert.match(appSource, /async function persistCaption\(target, caption = target\?\.caption\)/)
assert.match(appSource, /onCaptionCommit=\{\(caption\) => persistCaption\(selectedDay, caption\)\}/)
assert.match(appSource, /onClick=\{finishWithLatestCaption\}/)
assert.match(appSource, /key: 'colorWidth',[^\n]+min: 0\.5, max: 2/)
assert.match(appSource, /function FilmPicker\(\{ selectedFilmId, selectedLayoutId, unlockedFilmIds, lang, t, onSelect, onSelectLayout \}\)/)
assert.match(appSource, /const availableFilms = FILMS\.filter\(\(film\) => unlockedFilmIds\.includes\(film\.id\)\)/)
assert.match(appSource, /function FilmLayoutChoices\(/)
assert.match(appSource, /<FilmLayoutChoices filmId=\{selectedFilm\.id\} selectedLayoutId=\{selectedLayoutId\}/)
assert.match(appSource, /function FilmLayoutSupport\([\s\S]*?if \(!layoutIds\.length\) return null[\s\S]*?role="group" aria-label=\{t\.layoutSupportedLabel\}/, 'film support thumbnails must disappear when no additional layout is available')
assert.doesNotMatch(appSource, /function FilmLayoutSupport\([\s\S]*?<span>\{t\.layoutSupportedLabel\}<\/span>/, 'film support thumbnails must not render a visible support heading')
assert.match(appSource, /const additionalLayoutIds = getSupportedFilmLayoutIds\(film\.id\)\.filter\(\(layoutId\) => layoutId !== DEFAULT_LAYOUT_ID\)/, 'film support thumbnails must omit the default layout')
assert.match(appSource, /film-card-top \$\{additionalLayoutIds\.length \? 'has-layout-support' : ''\}/, 'film cards must center previews unless an additional layout is shown')
assert.match(appSource, /function PolaroidMediaLayout\(\{ geometry,/, 'full card previews must receive the shared layout geometry')
assert.match(appSource, /function PolaroidCard[\s\S]*?const geometry = getPolaroidLayoutGeometry\(resolvedLayoutId\)/, 'Polaroid cards must resolve one geometry contract for media, caption, and date')
assert.match(appSource, /function LayoutThumbnail[\s\S]*?<FilmPreviewCard className="layout-thumbnail-preview" filmId=\{filmId\} layoutId=\{layoutId\}/, 'layout thumbnails must be scaled instances of the shared full-card preview')
assert.match(appSource, /const \{ photo, sourceRects \} = renderModel\.geometry/, 'canvas export must consume the render model geometry')
assert.match(appSource, /drawCoverAt\(context, sourceImages\[index\], innerX, innerY, innerWidth, innerHeight\)/, 'all source photos must use the same centered cover crop in canvas exports')
assert.doesNotMatch(appSource, /drawContainAt|const drawSource =/, 'the mosaic layout must not diverge into a contain-only export path')
assert.match(appSource, /wrapCanvasText\(context, caption, captionLayout\.width, captionLayout\.maxLines\)/, 'canvas captions must wrap within the shared caption geometry')
assert.match(appSource, /multiline=\{selectedLayoutId === MOSAIC_LAYOUT_ID\}/, 'the corner layout editor must enable multiline input')
assert.match(appSource, /\? <textarea \{\.\.\.commonProps\} rows="3" \/>/, 'multiline captions must use a real textarea')
assert.match(appSource, /stored-polaroid-caption-slot" style=\{geometry\.captionCardStyle\}/, 'completed Polaroids must restore captions using their saved layout geometry')
assert.doesNotMatch(appSource, /mosaic-source-row|mosaic-source-column|mosaic-body/, 'layout geometry must not be duplicated as special-case JSX')
assert.doesNotMatch(appSource.slice(appSource.indexOf('function FilmPicker('), appSource.indexOf('function PolaroidCard')), /film-picker-current/, 'Rainbow Studio must use layout thumbnails instead of repeating the selected film name')
assert.match(appSource, /scopeFilmRenderSvg\(svg, scope\)/)
assert.match(appSource, /scopeFilmRenderSvg\(overlaySvg, scope\)/)
assert.match(appSource, /function updateEditorValue\(key, value\)/)
assert.match(appSource, /key === 'radius' \? preserveRainbowTopAnchor\(current, value\)/)
assert.match(appSource, /onChange=\{\(event\) => updateEditorValue\(activeControl\.key, Number\(event\.target\.value\)\)\}/)

const pickerStart = appSource.indexOf('function FilmPicker(')
const pickerEnd = appSource.indexOf('function PolaroidCard', pickerStart)
assert.ok(pickerStart >= 0 && pickerEnd > pickerStart, 'film picker source should be discoverable')
const pickerSource = appSource.slice(pickerStart, pickerEnd)
assert.doesNotMatch(pickerSource, /conditionKey|filmChallenge|pending/, 'Rainbow Studio film picker must only list available films')
assert.match(pickerSource, /scrolling \? 'is-scrolling' : ''/)
assert.match(pickerSource, /onPointerDown=\{prepareFilmScroll\}/)
assert.match(pickerSource, /onScroll=\{revealFilmScrollbar\}/)

const completedStart = appSource.indexOf('function CompletedPolaroid(')
const completedEnd = appSource.indexOf('function PolaroidCaption(', completedStart)
const completedSource = appSource.slice(completedStart, completedEnd)
assert.doesNotMatch(completedSource, /FilmPicker|FilmLayoutChoices|onSelectLayout/, 'completed Polaroids must stay baked and must not expose film or layout switching')

assert.match(appStyles, /\.editor-toolbar \{[^}]*grid-template-columns: repeat\(5, minmax\(52px, 1fr\)\)/)
assert.match(appStyles, /\.film-picker-options \{[^}]*overflow-x: auto;/)
assert.match(appStyles, /\.studio-workspace,\s*\.editor-dock,\s*\.film-picker,\s*\.film-picker-options \{ min-width: 0; \}/)
assert.match(appStyles, /\.film-picker-options \{ width: 100%; max-width: 100%; \}/)
assert.match(appStyles, /\.film-picker-options \{\s*scrollbar-color: transparent transparent;/)
assert.match(appStyles, /\.film-picker-options\.is-scrolling \{\s*scrollbar-color: var\(--purple\) transparent;/)
assert.match(appStyles, /\.film-surface-artwork > svg,\s*\.film-surface-overlay > svg \{ width: 100%; height: 100%; display: block; \}/)
assert.doesNotMatch(appStyles, /layout-thumbnail-(?:classic|mosaic-seven)|mosaic-source-row|mosaic-source-column|mosaic-body/, 'CSS must not maintain a second hard-coded copy of layout geometry')
assert.match(appStyles, /\.layout-thumbnail \{[^}]*container-type: inline-size;/, 'layout thumbnail frames must provide a sizing container for the shared preview scale')
assert.match(appStyles, /\.layout-thumbnail \{[^}]*background: transparent;[^}]*box-shadow: none;/, 'layout thumbnail wrappers must not draw a second frame around the preview')
assert.match(appStyles, /\.layout-thumbnail > \.layout-thumbnail-preview \{[^}]*width: 82px;[^}]*aspect-ratio: 2\/3;[^}]*transform: translate\(-50%, -50%\) rotate\(-2deg\) scale\(calc\(\(100cqw - 6px\) \/ 82px\)\);[^}]*transform-origin: center;[^}]*box-shadow: 3px 3px 0 var\(--ink\);/, 'layout thumbnails must scale the complete tilted preview with its hard shadow')
assert.match(appStyles, /\.film-card \.layout-thumbnail > \.layout-thumbnail-preview \{[^}]*width: 82px;[^}]*flex-basis: 82px;/, 'film-card preview sizing must not enlarge nested layout thumbnails')
assert.doesNotMatch(appStyles, /\.studio-layout-choices button(?:\.selected|:hover)?\s*\{/, 'studio layout buttons must reuse the shared film layout choice styling')
assert.doesNotMatch(appSource, /layout-thumbnail-(?:main|sources|caption)/, 'layout thumbnails must not duplicate the full preview with schematic blocks')
assert.match(appStyles, /\.polaroid-caption-placeholder \{[^}]*width: 23\.4cqw;[^}]*height: clamp\(1px, 4\.878cqw, 4px\);/, 'preview caption placeholders must scale in both dimensions with the shared card container')
assert.match(appStyles, /\.layout-thumbnail > \.layout-thumbnail-preview \.polaroid-caption-placeholder \{[^}]*width: 16cqw;[^}]*height: clamp\(1\.5px, 3\.4cqw, 2\.5px\);/, 'layout thumbnail caption placeholders must stay finer than the full preview after the card is scaled')
assert.doesNotMatch(appStyles, /\.layout-mosaic-seven \.polaroid-source-image img/, 'all layouts must share the same centered cover crop for source photos')
assert.match(appSource, /canvas-stage"><div className="canvas-source-actions">[\s\S]*?<PolaroidCard className="composition-canvas"/, 'background actions must live on the studio stage rather than inside the main photo')
assert.match(appStyles, /\.canvas-source-actions \{[^}]*top: 16px;[^}]*right: 18px;[^}]*flex-direction: column;/, 'background actions must stay vertically stacked in the upper-right corner of the studio stage')
assert.match(appStyles, /@media \(max-width: 760px\)[\s\S]*?\.canvas-stage \{ padding: 12px 15px 10px; \}[\s\S]*?\.canvas-source-actions \{ top: 12px; right: 15px; width: auto; flex-direction: column; gap: 5px; \}/, 'small screens must keep the Polaroid centered while actions stay vertically stacked in a compact icon rail')
assert.match(appStyles, /@media \(max-width: 760px\)[\s\S]*?\.composition-canvas\.polaroid-card \{ max-width: calc\(100% - 104px\); \}/, 'small screens must leave a black-background lane beside the centered Polaroid for the vertical actions')
assert.match(appStyles, /\.canvas-source-actions span \{ display: none;/, 'studio background action labels must be visually hidden so only icons remain')
assert.match(appStyles, /\.film-card-top \{[^}]*justify-content: center;/, 'film previews must center when no additional layout is shown')
assert.match(appStyles, /\.film-card-top \{[^}]*gap: 8px;/, 'film previews and support layouts must keep a compact separation')
assert.match(appStyles, /\.film-card-top\.has-layout-support \{[^}]*justify-content: flex-start;/, 'film previews must align to the left when support layouts occupy the right side')
assert.match(appStyles, /\.film-layout-support \{[^}]*flex-direction: column;[^}]*padding-left: 0;/, 'film support layouts must keep the previews flush to the left without a divider')
assert.doesNotMatch(appStyles, /\.film-layout-support \{[^}]*border-left:/, 'film support layouts must not render a divider')
assert.match(appStyles, /\.film-layout-support > div \{[^}]*flex-direction: column;/, 'film support thumbnails must form a vertical list')
assert.match(appStyles, /\.film-layout-support-item \{[^}]*width: 36px;[^}]*min-height: 54px;[^}]*padding: 0;[^}]*border: 0;[^}]*background: transparent;[^}]*box-shadow: none;/, 'additional layout thumbnails must render without an inner frame or background')
assert.match(appStyles, /\.film-layout-support-item \.layout-thumbnail \{[^}]*width: 36px;/, 'additional layout thumbnails must be enlarged and shifted toward the divider')
assert.doesNotMatch(appStyles, /\.editor-dock \{[^}]*box-shadow: [^;}]*rgba\(255,79,186/, 'the editor dock must not add a purple separator below the studio background')
assert.match(appStyles, /\.layout-mosaic-seven \.polaroid-caption-text, \.layout-mosaic-seven \.polaroid-caption-input \{[^}]*overflow-wrap: anywhere;[^}]*white-space: pre-wrap;/, 'corner-layout captions must wrap naturally')
assert.match(appStyles, /\.film-picker-heading strong,\s*\.film-picker-current,\s*\.film-option-name \{[^}]*overflow: visible;[^}]*overflow-wrap: anywhere;[^}]*white-space: normal;/)

console.log('Film challenge UI: Rainbow Studio only lists unlocked films, keeps challenge notices in the bookmark, and supports anchored radius controls.')
